require "../spec_helper"

private def convention(path : String, frontmatter : String) : AgentApropos::Convention
  AgentApropos::Convention.parse(path, "---\n#{frontmatter}\n---\nbody\n")
end

describe AgentApropos::Skills do
  describe "ROOTS" do
    it "is every distinct skill_root across Agents::ALL, in agent order" do
      AgentApropos::Skills::ROOTS.should eq(
        [Path[".claude", "skills"], Path[".gemini", "skills"], Path[".codex", "skills"]]
      )
    end
  end

  describe ".slug_for" do
    it "is the filename without its .md extension" do
      AgentApropos::Skills.slug_for("docs/conventions/workflows/ship-a-feature.md")
        .should eq("ship-a-feature")
    end
  end

  describe ".wrappers" do
    it "renders name + verbatim description with a banner and a source pointer" do
      conventions = [convention("docs/conventions/workflows/foo.md",
        %(skill: true\ndescription: "Use when foo"))]

      wrappers = AgentApropos::Skills.wrappers(conventions)
      wrappers.keys.should eq(["foo"])
      wrappers["foo"].should eq(<<-SKILL + "\n")
        ---
        name: foo
        description: Use when foo
        ---

        <!-- GENERATED by `agent-apropos generate` — do not edit. Edit the source doc instead. -->

        Read `docs/conventions/workflows/foo.md` and follow it.
        SKILL
    end

    it "inlines the doc body instead of a pointer when the source lives outside the repo" do
      conventions = [convention("../shared-conventions/workflows/foo.md",
        %(skill: true\ndescription: "Use when foo"))]

      wrapper = AgentApropos::Skills.wrappers(conventions)["foo"]
      wrapper.should_not contain("Read `")
      wrapper.should contain("body")
    end

    it "inlines the body's exact bytes, not stripped, when the source lives outside the repo" do
      text = "---\nskill: true\ndescription: \"Use when foo\"\n---\n# Foo\n\ncontent line   \n\n\n"
      body = AgentApropos::Frontmatter.split(text)[1]
      conventions = [AgentApropos::Convention.parse("../shared-conventions/workflows/foo.md", text)]

      wrapper = AgentApropos::Skills.wrappers(conventions)["foo"]
      wrapper.should end_with(body)
    end

    it "appends a trailing newline when inlining a body that lacks one" do
      text = "---\nskill: true\ndescription: \"Use when foo\"\n---\nno trailing newline"
      conventions = [AgentApropos::Convention.parse("../shared-conventions/workflows/foo.md", text)]

      wrapper = AgentApropos::Skills.wrappers(conventions)["foo"]
      wrapper.should end_with("no trailing newline\n")
    end

    it "ignores docs without skill: true" do
      conventions = [
        convention("docs/conventions/a.md", %(paths: ["src/**"])),
        convention("docs/conventions/b.md", %(contents: ['\\bx\\b'])),
      ]
      AgentApropos::Skills.wrappers(conventions).should be_empty
    end

    it "quotes a description that needs YAML escaping, byte-stably" do
      conventions = [convention("docs/conventions/workflows/q.md",
        %(skill: true\ndescription: "Use when: a \\"quoted\\" case"))]
      wrapper = AgentApropos::Skills.wrappers(conventions)["q"]
      wrapper.should contain(%(description: 'Use when: a "quoted" case'))
    end

    it "raises on a slug collision across directories" do
      conventions = [
        convention("docs/conventions/workflows/dup.md", %(skill: true\ndescription: "Use when A")),
        convention("docs/conventions/other/dup.md", %(skill: true\ndescription: "Use when B")),
      ]
      expect_raises(AgentApropos::Skills::Error, /slug collision on 'dup'/) do
        AgentApropos::Skills.wrappers(conventions)
      end
    end

    it "raises when a skill doc has no description" do
      conventions = [convention("docs/conventions/workflows/n.md", %(skill: true))]
      expect_raises(AgentApropos::Skills::Error, /no `description`/) do
        AgentApropos::Skills.wrappers(conventions)
      end
    end
  end

  describe ".active_roots" do
    it "is empty when no agent's init file exists" do
      fs = InMemoryFS.new
      AgentApropos::Skills.active_roots(Path["/repo"], fs).should be_empty
    end

    it "activates .claude/skills when Claude Code is wired" do
      fs = InMemoryFS.new({"/repo/.claude/settings.json" => "{}"})
      AgentApropos::Skills.active_roots(Path["/repo"], fs).should eq(Set{Path[".claude", "skills"]})
    end

    it "activates .claude/skills when only OpenCode is wired" do
      fs = InMemoryFS.new({"/repo/.opencode/plugins/agent-apropos.js" => "// js"})
      AgentApropos::Skills.active_roots(Path["/repo"], fs).should eq(Set{Path[".claude", "skills"]})
    end

    it "activates .claude/skills when only Copilot is wired" do
      fs = InMemoryFS.new({"/repo/.github/hooks/agent-apropos.json" => "{}"})
      AgentApropos::Skills.active_roots(Path["/repo"], fs).should eq(Set{Path[".claude", "skills"]})
    end

    it "activates .gemini/skills only when Gemini CLI is wired" do
      fs = InMemoryFS.new({"/repo/.gemini/settings.json" => "{}"})
      AgentApropos::Skills.active_roots(Path["/repo"], fs).should eq(Set{Path[".gemini", "skills"]})
    end

    it "activates .codex/skills only when Codex CLI is wired" do
      fs = InMemoryFS.new({"/repo/.codex/hooks.json" => "{}"})
      AgentApropos::Skills.active_roots(Path["/repo"], fs).should eq(Set{Path[".codex", "skills"]})
    end

    it "activates every root when every agent is wired" do
      fs = InMemoryFS.new({
        "/repo/.claude/settings.json" => "{}",
        "/repo/.gemini/settings.json" => "{}",
        "/repo/.codex/hooks.json"     => "{}",
      })
      AgentApropos::Skills.active_roots(Path["/repo"], fs).should eq(AgentApropos::Skills::ROOTS.to_set)
    end
  end
end
