#!/usr/bin/env bats
#
# Tests for scripts/mutate.sh. Each case builds a throwaway git repo and runs the
# real script in it, with the engine, the Crystal toolchain and `timeout` stubbed
# on PATH.

bats_require_minimum_version 1.5.0

bats_load_library bats-support
bats_load_library bats-assert

SCRIPT_UNDER_TEST() { printf '%s' "$BATS_TEST_DIRNAME/../scripts/mutate.sh"; }

setup() {
  REPO="$BATS_TEST_TMPDIR/repo"
  STUBS="$BATS_TEST_TMPDIR/stubs"
  export STUB_LOG="$BATS_TEST_TMPDIR/crystal.log"
  : >"$STUB_LOG"

  make_stubs
  make_repo
}

# --- stubs -----------------------------------------------------------------

make_stubs() {
  mkdir -p "$STUBS"

  cat >"$STUBS/mutate" <<'STUB'
#!/usr/bin/env bash
set -euo pipefail
source=""; mdir="."; lines=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    --mutantDir) mdir="$2"; shift 2 ;;
    --lines) lines="$2"; shift 2 ;;
    --only) shift 2 ;;
    --cmd) printf '%s' "$2" >"$STUB_CMD_SEEN"; shift 2 ;;
    -*) shift ;;
    *) source="$1"; shift ;;
  esac
done
[ -n "$lines" ] && cp "$lines" "$STUB_LINES_SEEN"

if [ -n "${STUB_INSERTS_A_LINE:-}" ]; then
  base="$(basename "${source%.cr}")"
  awk -v l="2" 'NR == l { print; print "  break"; next } { print }' "$source" \
    >"$mdir/$base.mutant.0.cr"
  echo "PROCESSING MUTANT: 2: original  ==>  original\n  break...VALID [written to $mdir/$base.mutant.0.cr]"
  echo "1 MUTANTS GENERATED BY RULES"
  exit 0
fi

if [ -n "${STUB_ENGINE_EXITS_NONZERO:-}" ]; then echo "boom" >&2; exit 3; fi
if [ -n "${STUB_ENGINE_RULES_MISSING:-}" ]; then
  # The real engine prints this and exits 0.
  echo "COULD NOT FIND RULE FILE nowhere.rules!  SKIPPING..."
  echo "0 MUTANTS GENERATED BY RULES"
  exit 0
fi

base="$(basename "${source%.cr}")"
total="$(wc -l <"$source")"
n=0
for line in $(seq 1 "$total"); do
  if [ -n "$lines" ] && ! grep -qx "[[:space:]]*$line[[:space:]]*" "$lines"; then continue; fi
  awk -v l="$line" -v text="${STUB_MUTANT_TEXT:-MUTANT}" \
    'NR == l { print text; next } { print }' "$source" >"$mdir/$base.mutant.$n.cr"
  echo "PROCESSING MUTANT: $line: original  ==>  ${STUB_MUTANT_TEXT:-MUTANT}...VALID"
  n=$((n + 1))
done
echo "$n MUTANTS GENERATED BY RULES"
STUB

  cat >"$STUBS/crystal" <<'STUB'
#!/usr/bin/env bash
set -euo pipefail
echo "$*" >>"$STUB_LOG"
case "${1:-}" in
  tool) cat >/dev/null; exit 0 ;;
  spec) ;;
  *) exit 0 ;;
esac

source_text="$(find src -name '*.cr' -exec cat {} + 2>/dev/null || true)"

if [ -n "${STUB_INTERRUPT_ON_MUTANT:-}" ] && [[ "$source_text" == *MUTANT* ]]; then
  kill -INT "$PPID"
  sleep 5
  exit 0
fi

if [ -n "${STUB_RED_BASELINE:-}" ]; then exit 1; fi
[[ "$source_text" == *MUTANT* ]] || exit 0

# A bare `crystal spec` is the whole suite; `crystal spec <file>` is a sibling.
if [ "$#" -eq 1 ]; then
  [ -n "${STUB_FULL_SUITE_KILLS:-}" ] && exit 1
  exit 0
fi
[ -n "${STUB_SIBLING_SURVIVES:-}" ] && exit 0
exit 1
STUB

  cat >"$STUBS/timeout" <<'STUB'
#!/usr/bin/env bash
if find src -name '*.cr' -exec grep -lq MUTANT {} + 2>/dev/null; then
  [ -n "${STUB_MUTANT_TIMES_OUT:-}" ] && exit 124
  # A bare `crystal spec` is the whole-suite re-check.
  if [ -n "${STUB_SUITE_TIMES_OUT:-}" ] && [ "$#" -eq 4 ]; then exit 124; fi
fi
while [ "$#" -gt 0 ]; do
  case "$1" in
    -*) shift ;;
    *) shift; break ;;
  esac
done
exec "$@"
STUB

  chmod +x "$STUBS/mutate" "$STUBS/crystal" "$STUBS/timeout"
  export STUB_LINES_SEEN="$BATS_TEST_TMPDIR/lines-seen"
  export STUB_CMD_SEEN="$BATS_TEST_TMPDIR/cmd-seen"
}

# --- fixture repo ----------------------------------------------------------

make_repo() {
  mkdir -p "$REPO/src/lib" "$REPO/spec/lib" "$REPO/tool/mutate" "$REPO/docs"
  git -C "$REPO" init --quiet
  git -C "$REPO" config user.email 'test@example.com'
  git -C "$REPO" config user.name 'Test'

  cat >"$REPO/src/lib/thing.cr" <<'CR'
def widen(value)
  value + 1
end
CR
  printf 'it works\n' >"$REPO/spec/lib/thing_spec.cr"
  # Committed up front, so the new-file case's diff is the source file alone.
  printf 'it works\n' >"$REPO/spec/lib/fresh_spec.cr"
  printf 'a ==> b\n' >"$REPO/tool/mutate/crystal.rules"
  printf '{"equivalent":[]}\n' >"$REPO/tool/mutate/ignore.json"
  printf '{"exempt":[]}\n' >"$REPO/tool/mutate/no-spec.json"
  set_clean src/lib/thing.cr
  printf '# docs\n' >"$REPO/docs/readme.md"

  git -C "$REPO" add -A
  git -C "$REPO" commit --quiet -m 'base'
  BASE="$(git -C "$REPO" rev-parse HEAD)"
}

set_clean() { jq -n '$ARGS.positional | {clean: .}' --args "$@" >"$REPO/tool/mutate/clean.json"; }

add_clean() {
  jq --arg path "$1" '.clean += [$path]' "$REPO/tool/mutate/clean.json" >"$BATS_TEST_TMPDIR/c.json"
  mv "$BATS_TEST_TMPDIR/c.json" "$REPO/tool/mutate/clean.json"
}

set_exempt() {
  jq -n --arg path "$1" --arg reason "$2" '{exempt: [{path: $path, reason: $reason}]}' \
    >"$REPO/tool/mutate/no-spec.json"
}

set_ignore() {
  jq -n --arg path "$1" --argjson occurrence "$2" --arg original "$3" --arg mutated "$4" \
    --arg reason "$5" \
    '{equivalent: [{path: $path, occurrence: $occurrence, original: $original, mutated: $mutated, reason: $reason}]}' \
    >"$REPO/tool/mutate/ignore.json"
}

commit_all() {
  git -C "$REPO" add -A
  git -C "$REPO" commit --quiet -m "${1:-change}"
}

run_gate() {
  cd "$REPO"
  PATH="$STUBS:$PATH" run --separate-stderr bash "$(SCRIPT_UNDER_TEST)" "$@"
}

spec_runs() { grep -c '^spec' "$STUB_LOG" || true; }

# --- scope -----------------------------------------------------------------

@test "a diff touching only documentation exits 0 without running a spec" {
  printf '# docs, revised\n' >"$REPO/docs/readme.md"
  commit_all

  run_gate --base "$BASE"

  assert_success
  assert_output --partial 'nothing to mutate'
  assert_equal "$(spec_runs)" "0"
}

@test "a diff that only deletes source lines exits 0" {
  printf 'def widen(value)\nend\n' >"$REPO/src/lib/thing.cr"
  commit_all

  run_gate --base "$BASE"

  assert_success
  assert_output --partial 'nothing to mutate'
}

@test "a newly added source file is mutated in full" {
  printf 'one\ntwo\nthree\n' >"$REPO/src/lib/fresh.cr"
  commit_all

  run_gate --base "$BASE"

  assert_success
  assert_output --partial 'src/lib/fresh.cr (whole file'
  assert_output --partial '3 mutants generated'
}

@test "a changed source line is mutated and a killed mutant passes the gate" {
  printf 'def widen(value)\n  value + 2\nend\n' >"$REPO/src/lib/thing.cr"
  commit_all

  run_gate --base "$BASE"

  assert_success
  assert_output --partial '1 mutants generated, 1 compiled, 1 killed, 0 surviving'
  assert_equal "$(tr -d ' \n' <"$STUB_LINES_SEEN")" "2"
}

@test "an inserted line is reported as one folded mutation" {
  export STUB_SIBLING_SURVIVES=1 STUB_INSERTS_A_LINE=1
  printf 'def widen(value)\n  value + 2\nend\n' >"$REPO/src/lib/thing.cr"
  commit_all

  run_gate --base "$BASE"

  assert_failure 1
  [[ "$stderr" == *'was: value + 2'* ]] || fail "expected the original line: $stderr"
  [[ "$stderr" == *'now: value + 2\nbreak'* ]] || fail "expected the folded span: $stderr"
}

# --- survivors -------------------------------------------------------------

@test "a surviving mutant fails the gate and names the mutation" {
  export STUB_SIBLING_SURVIVES=1
  printf 'def widen(value)\n  value + 2\nend\n' >"$REPO/src/lib/thing.cr"
  commit_all

  run_gate --base "$BASE"

  assert_failure 1
  [[ "$stderr" == *'src/lib/thing.cr:2'* ]] || fail "expected the report to name the line: $stderr"
  [[ "$stderr" == *'value + 2'* ]] || fail "expected the report to show the original: $stderr"
  [[ "$stderr" == *'MUTANT'* ]] || fail "expected the report to show the mutation: $stderr"
}

@test "a mutant killed only by the full suite is scored killed, not reported" {
  export STUB_SIBLING_SURVIVES=1 STUB_FULL_SUITE_KILLS=1
  printf 'def widen(value)\n  value + 2\nend\n' >"$REPO/src/lib/thing.cr"
  commit_all

  run_gate --base "$BASE"

  assert_success
  assert_output --partial '1 killed, 0 surviving'
}

@test "a mutant whose spec run times out is counted as killed" {
  export STUB_SIBLING_SURVIVES=1 STUB_MUTANT_TIMES_OUT=1
  printf 'def widen(value)\n  value + 2\nend\n' >"$REPO/src/lib/thing.cr"
  commit_all

  run_gate --base "$BASE"

  assert_success
  assert_output --partial '1 killed, 0 surviving'
}

@test "a spec target that fails on unmutated source aborts with its own error" {
  export STUB_RED_BASELINE=1
  printf 'def widen(value)\n  value + 2\nend\n' >"$REPO/src/lib/thing.cr"
  commit_all

  run_gate --base "$BASE"

  assert_failure 2
  [[ "$stderr" == *'does not pass against unmutated source'* ]] ||
    fail "expected the red-baseline error: $stderr"
}

@test "the source file is restored when the run is interrupted mid-mutant" {
  export STUB_INTERRUPT_ON_MUTANT=1
  printf 'def widen(value)\n  value + 2\nend\n' >"$REPO/src/lib/thing.cr"
  commit_all
  before="$(cat "$REPO/src/lib/thing.cr")"

  run_gate --base "$BASE"

  assert_equal "$(cat "$REPO/src/lib/thing.cr")" "$before"
}

# --- ignore list -----------------------------------------------------------

@test "a survivor matching a reviewed ignore-list entry passes the gate" {
  export STUB_SIBLING_SURVIVES=1
  printf 'def widen(value)\n  value + 2\nend\n' >"$REPO/src/lib/thing.cr"
  set_ignore src/lib/thing.cr 1 'value + 2' MUTANT 'cannot change observable behaviour'
  commit_all

  run_gate --base "$BASE"

  assert_success
  assert_output --partial '0 surviving'
}

@test "an ignore-list entry suppresses only the occurrence it names" {
  export STUB_SIBLING_SURVIVES=1
  printf 'def widen(value)\n  value + 2\n  value + 2\nend\n' >"$REPO/src/lib/thing.cr"
  set_ignore src/lib/thing.cr 1 'value + 2' MUTANT 'reviewed: the first one only'
  commit_all

  run_gate --base "$BASE"

  assert_failure 1
  assert_equal "$(grep -c 'src/lib/thing.cr:' <<<"$stderr")" "1"
  [[ "$stderr" == *'src/lib/thing.cr:3'* ]] || fail "expected the unreviewed occurrence: $stderr"
}

@test "an ignore-list entry whose original text is gone is reported as stale" {
  set_ignore src/lib/thing.cr 1 'value + 999' MUTANT 'no longer present'
  commit_all

  run_gate --base "$BASE"

  assert_failure 2
  [[ "$stderr" == *'no longer matches any line'* ]] || fail "expected a stale-entry error: $stderr"
}

# --- reviewed lists --------------------------------------------------------

@test "a tracked source file with neither sibling spec nor exemption fails the run" {
  printf 'lonely\n' >"$REPO/src/lib/orphan.cr"
  commit_all

  run_gate --base "$BASE"

  assert_failure 2
  [[ "$stderr" == *'src/lib/orphan.cr has no sibling spec'* ]] ||
    fail "expected the missing-sibling error: $stderr"
}

@test "a reviewed exemption stands in for a missing sibling spec" {
  export STUB_FULL_SUITE_KILLS=1
  printf 'lonely\n' >"$REPO/src/lib/orphan.cr"
  set_exempt src/lib/orphan.cr 'no mutable construct'
  commit_all

  run_gate --base "$BASE"

  assert_success
}

@test "an exemption naming a file that is no longer tracked is reported as stale" {
  set_exempt src/lib/gone.cr 'deleted last week'
  commit_all

  run_gate --base "$BASE"

  assert_failure 2
  [[ "$stderr" == *'no longer a tracked source file'* ]] || fail "expected a stale-exemption error: $stderr"
}

@test "a clean-list entry naming a file that no longer exists is reported as stale" {
  add_clean src/lib/gone.cr
  commit_all

  run_gate --base "$BASE"

  assert_failure 2
  [[ "$stderr" == *'no longer exists'* ]] || fail "expected a stale-clean-list error: $stderr"
}

@test "a module with no sibling spec falls back to the whole suite" {
  export STUB_FULL_SUITE_KILLS=1
  printf 'lonely\n' >"$REPO/src/lib/orphan.cr"
  set_exempt src/lib/orphan.cr 'declaration only'
  commit_all

  run_gate --base "$BASE"

  assert_success
  grep -qx 'spec' "$STUB_LOG" || fail "expected a bare 'crystal spec' run: $(cat "$STUB_LOG")"
}

@test "a survivor in a no-sibling module is reported, not scored killed" {
  printf 'lonely\n' >"$REPO/src/lib/orphan.cr"
  set_exempt src/lib/orphan.cr 'declaration only'
  commit_all

  run_gate --base "$BASE"

  assert_failure 1
  [[ "$stderr" == *'src/lib/orphan.cr:1'* ]] || fail "expected the survivor to be named: $stderr"
}

@test "the compile gate builds the entry point, never the spec directory" {
  printf 'lonely\n' >"$REPO/src/lib/orphan.cr"
  set_exempt src/lib/orphan.cr 'declaration only'
  commit_all

  run_gate --base "$BASE"

  refute_output --partial 'no-codegen spec'
  grep -q 'no-codegen src/agent_apropos.cr' "$STUB_CMD_SEEN" ||
    fail "compile gate did not target the entry point: $(cat "$STUB_CMD_SEEN")"
}

# --- spec-file changes ------------------------------------------------------

@test "changing a module's spec mutates that module in full" {
  printf 'it works, harder\n' >"$REPO/spec/lib/thing_spec.cr"
  commit_all

  run_gate --base "$BASE"

  assert_success
  assert_output --partial 'src/lib/thing.cr (whole file; its spec changed)'
  assert_output --partial '3 mutants generated'
}

# The widening has no condition: a module whose spec changed is mutated in full
# whether or not it already carries a clean record.
@test "changing the spec of a file with no clean record still mutates it in full" {
  set_clean
  printf 'it works, harder\n' >"$REPO/spec/lib/thing_spec.cr"
  commit_all

  run_gate --base "$BASE"

  assert_success
  assert_output --partial 'src/lib/thing.cr (whole file'
}

# The boy-scout rule: touch a file with no clean record and the whole file is in
# scope, so bringing it to zero survivors is part of the change.
@test "a changed file with no clean record is mutated in full" {
  set_clean
  printf 'def widen(value)\n  value + 2\nend\n' >"$REPO/src/lib/thing.cr"
  commit_all

  run_gate --base "$BASE"

  assert_success
  assert_output --partial 'src/lib/thing.cr (whole file; no 100% record yet)'
  assert_output --partial '3 mutants generated'
}

@test "a changed file with a clean record is mutated by changed lines only" {
  printf 'def widen(value)\n  value + 2\nend\n' >"$REPO/src/lib/thing.cr"
  commit_all

  run_gate --base "$BASE"

  assert_success
  assert_output --partial 'src/lib/thing.cr (1 changed lines)'
  assert_equal "$(tr -d ' \n' <"$STUB_LINES_SEEN")" "2"
}

# Earning the record has to be visible, or nobody adds the entry and every later
# change to that file keeps paying whole-file cost.
@test "a file that reaches zero survivors is named for the clean list" {
  set_clean
  printf 'def widen(value)\n  value + 2\nend\n' >"$REPO/src/lib/thing.cr"
  commit_all

  run_gate --base "$BASE"

  assert_success
  assert_output --partial 'Record them in tool/mutate/clean.json'
  assert_output --partial '  src/lib/thing.cr'
}

@test "a file with survivors is not named for the clean list" {
  export STUB_SIBLING_SURVIVES=1
  set_clean
  printf 'def widen(value)\n  value + 2\nend\n' >"$REPO/src/lib/thing.cr"
  commit_all

  run_gate --base "$BASE"

  assert_failure 1
  refute_output --partial 'Record them in'
}

# --- the engine's own failures ---------------------------------------------

@test "an engine that exits non-zero fails the run" {
  export STUB_ENGINE_EXITS_NONZERO=1
  printf 'def widen(value)\n  value + 2\nend\n' >"$REPO/src/lib/thing.cr"
  commit_all

  run_gate --base "$BASE"

  assert_failure 2
  [[ "$stderr" == *'mutation engine exited 3'* ]] || fail "expected the engine's status: $stderr"
}

@test "an engine that generates nothing fails the run even when it exits 0" {
  export STUB_ENGINE_RULES_MISSING=1
  printf 'def widen(value)\n  value + 2\nend\n' >"$REPO/src/lib/thing.cr"
  commit_all

  run_gate --base "$BASE"

  assert_failure 2
  [[ "$stderr" == *'did not load cleanly'* ]] || fail "expected a rules-load error: $stderr"
}

@test "a missing rules file fails before any spec runs" {
  rm "$REPO/tool/mutate/crystal.rules"
  commit_all

  run_gate --base "$BASE"

  assert_failure 2
  [[ "$stderr" == *'crystal.rules is missing'* ]] || fail "expected a missing-rules error: $stderr"
  assert_equal "$(spec_runs)" "0"
}

@test "git config that rewrites diff text does not change the line set" {
  printf '#!/usr/bin/env bash\necho "custom diff output"\n' >"$STUBS/fake-diff"
  chmod +x "$STUBS/fake-diff"
  git -C "$REPO" config diff.external "$STUBS/fake-diff"
  git -C "$REPO" config diff.noprefix true
  git -C "$REPO" config diff.mnemonicPrefix true
  printf 'def widen(value)\n  value + 2\nend\n' >"$REPO/src/lib/thing.cr"
  commit_all

  run_gate --base "$BASE"

  assert_success
  assert_equal "$(tr -d ' \n' <"$STUB_LINES_SEEN")" "2"
}

# The full-suite re-check's status used to be discarded, so a suite that always
# timed out scored every mutant killed while the guard saw no timeouts at all.
@test "a full-suite re-check that times out counts toward the degraded guard" {
  export STUB_SIBLING_SURVIVES=1 STUB_SUITE_TIMES_OUT=1
  printf 'one\ntwo\nthree\nfour\nfive\nsix\n' >"$REPO/src/lib/thing.cr"
  commit_all

  run_gate --base "$BASE"

  assert_failure 2
  [[ "$stderr" == *'too degraded to trust'* ]] || fail "expected a degraded-run error: $stderr"
}

@test "a storm of timing-out mutants fails rather than reading as all killed" {
  export STUB_SIBLING_SURVIVES=1 STUB_MUTANT_TIMES_OUT=1
  printf 'one\ntwo\nthree\nfour\nfive\nsix\n' >"$REPO/src/lib/thing.cr"
  commit_all

  run_gate --base "$BASE"

  assert_failure 2
  [[ "$stderr" == *'too degraded to trust'* ]] || fail "expected a degraded-run error: $stderr"
}

# --- several targets in one run --------------------------------------------

@test "two changed source files are both mutated" {
  printf 'it works\n' >"$REPO/spec/lib/second_spec.cr"
  add_clean src/lib/second.cr
  printf 'def narrow(value)\n  value - 1\nend\n' >"$REPO/src/lib/second.cr"
  git -C "$REPO" add -A && git -C "$REPO" commit --quiet -m 'sibling for second'
  BASE="$(git -C "$REPO" rev-parse HEAD)"
  printf 'def widen(value)\n  value + 2\nend\n' >"$REPO/src/lib/thing.cr"
  printf 'def narrow(value)\n  value - 2\nend\n' >"$REPO/src/lib/second.cr"
  commit_all

  run_gate --base "$BASE"

  assert_success
  assert_output --partial 'src/lib/thing.cr'
  assert_output --partial 'src/lib/second.cr'
  assert_output --partial '2 mutants generated'
}

@test "a module whose source and spec both changed is mutated in full, not by line" {
  printf 'def widen(value)\n  value + 2\nend\n' >"$REPO/src/lib/thing.cr"
  printf 'it works, harder\n' >"$REPO/spec/lib/thing_spec.cr"
  commit_all

  run_gate --base "$BASE"

  assert_success
  assert_output --partial 'src/lib/thing.cr (whole file'
  assert_output --partial '3 mutants generated'
}

@test "source paths that flatten to one key keep separate backups" {
  mkdir -p "$REPO/src/lib/a" "$REPO/spec/lib/a"
  printf 'first\n' >"$REPO/src/lib/a/b.cr"
  printf 'second\n' >"$REPO/src/lib/a_b.cr"
  printf 'it works\n' >"$REPO/spec/lib/a/b_spec.cr"
  printf 'it works\n' >"$REPO/spec/lib/a_b_spec.cr"
  commit_all

  run_gate --base "$BASE"

  assert_success
  assert_equal "$(cat "$REPO/src/lib/a/b.cr")" "first"
  assert_equal "$(cat "$REPO/src/lib/a_b.cr")" "second"
}

# --- the clean list has to be earned ---------------------------------------

# A change could otherwise add its own file to the list and collect
# changed-line-only scope on the strength of a claim nothing has checked.
@test "a clean entry added by this change does not count yet" {
  add_clean src/lib/orphan.cr
  printf 'lonely\nand untested\n' >"$REPO/src/lib/orphan.cr"
  printf 'it works\n' >"$REPO/spec/lib/orphan_spec.cr"
  commit_all

  run_gate --base "$BASE"

  assert_success
  assert_output --partial 'src/lib/orphan.cr (whole file; no 100% record yet)'
}

# Taking a file off the list is how you say it regressed, so that has to bite
# immediately rather than waiting for the base to catch up.
@test "a clean entry removed by this change stops counting immediately" {
  set_clean
  printf 'def widen(value)\n  value + 2\nend\n' >"$REPO/src/lib/thing.cr"
  commit_all

  run_gate --base "$BASE"

  assert_success
  assert_output --partial 'src/lib/thing.cr (whole file; no 100% record yet)'
}

# `grep -q` exits at the first match, so git takes SIGPIPE finishing the write
# and `pipefail` turns the whole probe non-zero — reporting a broken diff on a
# perfectly good large one. Needs a diff bigger than a pipe buffer to show up,
# so the bulk here is deletions: lots of diff text, no lines to mutate.
@test "a diff too large for a pipe buffer is still parsed" {
  seq 1 40000 | sed 's/^/# line /' >"$REPO/src/lib/bulk.cr"
  printf 'it works\n' >"$REPO/spec/lib/bulk_spec.cr"
  add_clean src/lib/bulk.cr
  git -C "$REPO" add -A && git -C "$REPO" commit --quiet -m bulk
  BASE="$(git -C "$REPO" rev-parse HEAD)"

  printf '# line 1\n' >"$REPO/src/lib/bulk.cr"
  printf 'def widen(value)\n  value + 2\nend\n' >"$REPO/src/lib/thing.cr"
  commit_all

  run_gate --base "$BASE"

  assert_success
  refute_output --partial 'no line set can be derived'
  assert_output --partial 'src/lib/thing.cr (1 changed lines)'
}

# --- the engine's scratch ---------------------------------------------------

# Quoting the patterns would hand `rm` the literal names and clean nothing.
@test "the engine's scratch files do not survive a run" {
  printf 'def widen(value)\n  value + 2\nend\n' >"$REPO/src/lib/thing.cr"
  commit_all
  touch "$REPO/.tmp_mutant.4242.cr" "$REPO/.um.mutant_output.4242"
  touch "$REPO/src/lib/thing.cr.um.backup.4242"

  run_gate --base "$BASE"

  assert_success
  [ ! -e "$REPO/.tmp_mutant.4242.cr" ] || fail "left .tmp_mutant.4242.cr behind"
  [ ! -e "$REPO/.um.mutant_output.4242" ] || fail "left .um.mutant_output.4242 behind"
  [ ! -e "$REPO/src/lib/thing.cr.um.backup.4242" ] || fail "left the engine's backup behind"
}

# --- arguments -------------------------------------------------------------

@test "--base with no ref is an error" {
  run_gate --base
  assert_failure 2
  [[ "$stderr" == *'needs a ref'* ]] || fail "expected a missing-ref error: $stderr"
}

@test "an unknown option is an error" {
  run_gate --nonsense
  assert_failure 2
  [[ "$stderr" == *'unknown option'* ]] || fail "expected an unknown-option error: $stderr"
}

@test "an explicit file that does not exist is an error" {
  run_gate src/lib/absent.cr
  assert_failure 2
  [[ "$stderr" == *'does not exist'* ]] || fail "expected a missing-file error: $stderr"
}

@test "--help prints the usage block without running anything" {
  run_gate --help
  assert_success
  assert_output --partial 'scripts/mutate.sh'
  assert_equal "$(spec_runs)" "0"
}

# --- base ref --------------------------------------------------------------

@test "no pull-request base ref is a distinct error, not an empty line set" {
  printf 'def widen(value)\n  value + 2\nend\n' >"$REPO/src/lib/thing.cr"
  commit_all
  unset GITHUB_BASE_REF

  run_gate

  assert_failure 2
  [[ "$stderr" == *'no base ref'* ]] || fail "expected the missing-base error: $stderr"
}

@test "GITHUB_BASE_REF supplies the base when no --base is passed" {
  git -C "$REPO" branch base-branch "$BASE"
  git -C "$REPO" update-ref refs/remotes/origin/base-branch "$BASE"
  printf 'def widen(value)\n  value + 2\nend\n' >"$REPO/src/lib/thing.cr"
  commit_all
  export GITHUB_BASE_REF=base-branch

  run_gate

  assert_success
  assert_output --partial '1 mutants generated'
}

@test "an explicit file argument mutates it in full, ignoring the diff" {
  run_gate src/lib/thing.cr

  assert_success
  assert_output --partial 'src/lib/thing.cr (whole file'
  assert_output --partial '3 mutants generated'
}
