require "./agent"

module AgentApropos
  module Agents
    class OpenCode < Agent
      PLUGIN_RELATIVE = Path[".opencode", "plugins", "agent-apropos.js"]

      def name : String
        "opencode"
      end

      def read?(payload : Hook::Payload) : Bool
        payload.tool_name == "read"
      end

      def config_relative : Path
        PLUGIN_RELATIVE
      end

      def skill_root : Path
        Path[".claude", "skills"]
      end

      protected def hook_check(repo_root : Path, fs : Filesystem, env : Environment) : Check
        unless env.which("opencode")
          return Check.new(:ok, "opencode", "not on PATH; skipped plugin check")
        end
        plugin = repo_root.join(PLUGIN_RELATIVE).to_s
        if fs.exists?(plugin)
          Check.new(:ok, "opencode", "plugin wired")
        else
          Check.new(:warn, "opencode", "plugin absent; run `agent-apropos init --tool opencode`")
        end
      end

      protected def config_content(existing : String?, options : Init::Options) : String
        plugin_content(options.allow_outside_repo, false)
      end

      # Re-renders rather than patches — see docs/design/agent-dialects.md's OpenCode section.
      def sync_shell_hook(existing : String?, label : String, wire : Bool) : String?
        allow_outside = existing.try(&.includes?(ALLOW_OUTSIDE_FLAG)) || false
        updated = plugin_content(allow_outside, wire)
        return existing if updated == existing
        updated
      end

      private def plugin_content(allow_outside_repo : Bool, wire_shell : Bool) : String
        hook_args = allow_outside_repo ? %(, "--allow-outside-repo") : ""
        shell_tool = wire_shell ? %(, "bash") : ""
        <<-JS
        // Generated by `agent-apropos init --tool opencode` — do not edit. Re-run to regenerate.
        //
        // Bridges agent-apropos's hook system into OpenCode using client.session.prompt
        // with noReply:true, which injects convention context into the conversation
        // without triggering an AI response.
        //
        // Scoped rules (path and/or content) inject only when the agent writes:
        // tool.execute.before carries the fragment about to be written, and
        // tool.execute.after carries it again for edits the before-hook missed.
        // A "read" injects nothing — it only tells agent-apropos that a
        // convention doc is already in context, so no write re-injects it, and
        // it is wired on tool.execute.after so a read that failed or was
        // denied never suppresses a rule it did not actually deliver.
        // Both fail open: any error produces no output and never blocks an edit.
        // See docs/conventions/README.md for the layer model.
        //
        // "bash" is wired onto both events the same way, only when a removal-
        // triggered convention exists (see Generate#pending_shell_hook_updates) —
        // its args carry `command`, not `filePath`, confirmed against a real
        // captured `tool.execute.after` payload, not upstream docs.

        export const AgentAproposPlugin = async ({ worktree, client }) => {
          // Session ID tracked through events; also read from input.sessionID when
          // the plugin event exposes it (undocumented but likely present).
          let sessionID = null

          async function callHook(sub, payload) {
            try {
              const proc = Bun.spawn(["agent-apropos", "hook", sub, "--tool", "opencode"#{hook_args}], {
                stdin: new Blob([JSON.stringify(payload)]),
                stdout: "pipe",
                cwd: worktree,
              })
              const text = await new Response(proc.stdout).text()
              const parsed = JSON.parse(text.trim())
              return parsed?.hookSpecificOutput?.additionalContext ?? ""
            } catch {
              return ""
            }
          }

          async function inject(sid, ctx) {
            if (!ctx || !sid) return
            try {
              await client.session.prompt({
                path: { id: sid },
                body: { noReply: true, parts: [{ type: "text", text: ctx }] },
              })
            } catch {
              // Fail open
            }
          }

          function makePayload(input, args) {
            return {
              session_id: input.sessionID ?? sessionID,
              cwd: worktree,
              tool_name: input.tool,
              tool_input: {
                file_path:  args?.filePath,
                content:    args?.content,
                new_string: args?.newString,
                offset:     args?.offset,
                limit:      args?.limit,
                command:    args?.command,
              },
            }
          }

          return {
            // Track session ID so inject() can call client.session.prompt.
            event: async ({ event }) => {
              const id = event.properties?.session?.id ?? event.properties?.id
              if (id && (event.type === "session.created" || event.type === "session.updated")) {
                sessionID = id
              }
            },

            // Inject BEFORE the write so the model sees the rule while still in
            // the current tool-processing turn, with the pending content so
            // content regexes match the fragment about to land. OpenCode
            // delivers the tool arguments in the SECOND callback parameter
            // (output.args) for tool.execute.before; older builds put them on
            // input.args. Read output first, fall back to input.
            "tool.execute.before": async (input, output) => {
              if (!["edit", "write", "apply_patch"#{shell_tool}].includes(input.tool)) return
              const args = output?.args ?? input.args
              if (!args?.filePath && !args?.command) return
              const ctx = await callHook("pre", makePayload(input, args))
              await inject(input.sessionID ?? sessionID, ctx)
            },

            // Inject AFTER the write as well, for rules the before-hook could
            // not resolve (an edit whose newString the before event omits).
            // "read" is handled here only, never before: this event fires once
            // the read has actually succeeded, so a denied or failed read
            // cannot suppress a rule. Here OpenCode carries args on input; the
            // same output-first fallback keeps this robust across versions.
            "tool.execute.after": async (input, output) => {
              if (!["edit", "write", "apply_patch", "read"#{shell_tool}].includes(input.tool)) return
              const args = output?.args ?? input.args
              if (!args?.filePath && !args?.command) return
              const ctx = await callHook("post", makePayload(input, args))
              await inject(input.sessionID ?? sessionID, ctx)
            },
          }
        }
        JS
      end
    end
  end
end
