require "yaml"
require "./conventions"
require "./agents"
require "./filesystem"

module AgentApropos
  # Skill wrapper generation: for every `skill: true` doc, emit a
  # `.claude/skills/<slug>/SKILL.md` whose frontmatter carries the doc's `name`
  # (its slug) and `description` verbatim, and whose body is a generated
  # banner plus a pointer back to the source doc — or, when the source lives
  # outside the repo (a custom `conventions_dir`, e.g. `../shared-docs`), the
  # doc's full body inlined instead. A pointer this thin only works if the
  # model actually follows it; that's reliable for a normal in-repo path (it
  # looks like anything else in the project) but was observed *not* to be for
  # an external one with `../` segments outside the visible workspace tree —
  # the model has no reason to trust or prioritize reading it. The wrappers
  # are the one *committed* generated artifact, so their bytes must be
  # stable — the `--check` gate byte-compares them.
  module Skills
    extend self

    # Raised on a slug collision (two skill docs sharing a filename) or a skill
    # doc missing its required `description`. `generate` fails closed on these.
    class Error < AgentApropos::Error
    end

    # Every directory a skill wrapper can be generated into, one per distinct
    # `Agents::Agent#skill_root` across `Agents::ALL` — see that method for
    # why OpenCode and GitHub Copilot CLI resolve to Claude Code's directory
    # instead of one of their own. Codex CLI's own `SKILL.md` frontmatter
    # shape — `name`/`description` — happens to be identical to Claude's,
    # confirmed live: a `.codex/skills/<slug>/SKILL.md` copy of the generated
    # Claude wrapper was picked up by a real Codex CLI run, where the same
    # content under `.claude/skills/` alone was not.
    ROOTS = Agents::ALL.map(&.skill_root).uniq!

    BANNER = "<!-- GENERATED by `agent-apropos generate` — do not edit. Edit the source doc instead. -->"

    # Roots worth writing/checking wrappers in right now: at least one agent
    # resolving to that root (via `#skill_root`) has its own init-generated
    # hook file present in the repo. `generate` and `lint` both use this so
    # neither scatters e.g. `.gemini/skills/` into a repo that never ran
    # `init --tool gemini` — only the tools actually wired via `init` see a
    # skills directory.
    def active_roots(repo_root : Path, fs : Filesystem) : Set(Path)
      Agents::ALL.select(&.configured?(repo_root, fs)).map(&.skill_root).to_set
    end

    # The desired wrapper file bodies, keyed by slug, for every skill doc in
    # `conventions`. Deterministic and idempotent. Raises on a collision or a
    # missing description.
    def wrappers(conventions : Array(Convention)) : Hash(String, String)
      sources = {} of String => String
      result = {} of String => String
      conventions.each do |convention|
        next unless convention.skill?
        slug = slug_for(convention.path)
        if existing = sources[slug]?
          raise Error.new(
            "skill slug collision on '#{slug}': #{existing} and #{convention.path}")
        end
        sources[slug] = convention.path
        result[slug] = render(convention, slug)
      end
      result
    end

    # The slug for a doc: its filename without the `.md` extension. Windows-aware
    # via `Path` rather than a hardcoded separator.
    def slug_for(path : String) : String
      Path[path].basename(".md")
    end

    private def render(convention : Convention, slug : String) : String
      description = convention.frontmatter.description
      if description.nil?
        raise Error.new("skill doc #{convention.path} has `skill: true` but no `description`")
      end

      String.build do |io|
        io << YAML.dump({"name" => slug, "description" => description})
        io << "---\n\n"
        io << BANNER << "\n\n"
        if escapes_repo?(convention.path)
          body = convention.body
          io << body
          io << "\n" unless body.ends_with?("\n")
        else
          io << "Read `" << convention.path << "` and follow it.\n"
        end
      end
    end

    # Whether a convention's repo-relative path climbs out of the repo (a
    # `../`-leading path — only possible via a custom `conventions_dir`).
    private def escapes_repo?(path : String) : Bool
      Path.posix(path).parts.first? == ".."
    end
  end
end
