require "yaml"
require "./conventions"
require "./agents"
require "./filesystem"

module AgentApropos
  module Skills
    extend self

    class Error < AgentApropos::Error
    end

    ROOTS = Agents::ALL.map(&.skill_root).uniq!

    BANNER = "<!-- GENERATED by `agent-apropos generate` — do not edit. Edit the source doc instead. -->"

    def active_roots(repo_root : Path, fs : Filesystem) : Set(Path)
      Agents::ALL.select(&.configured?(repo_root, fs)).map(&.skill_root).to_set
    end

    def wrappers(conventions : Array(Convention)) : Hash(String, String)
      sources = {} of String => String
      result = {} of String => String
      conventions.each do |convention|
        next unless convention.skill?
        slug = slug_for(convention.path)
        if existing = sources[slug]?
          raise Error.new(
            "skill slug collision on '#{slug}': #{existing} and #{convention.path}")
        end
        sources[slug] = convention.path
        result[slug] = render(convention, slug)
      end
      result
    end

    def slug_for(path : String) : String
      Path[path].basename(".md")
    end

    private def render(convention : Convention, slug : String) : String
      description = convention.frontmatter.description
      if description.nil?
        raise Error.new("skill doc #{convention.path} has `skill: true` but no `description`")
      end

      String.build do |io|
        io << YAML.dump({"name" => slug, "description" => description})
        io << "---\n\n"
        io << BANNER << "\n\n"
        if escapes_repo?(convention.path)
          body = convention.body
          io << body
          io << "\n" unless body.ends_with?("\n")
        else
          io << "Read `" << convention.path << "` and follow it.\n"
        end
      end
    end

    private def escapes_repo?(path : String) : Bool
      Path.posix(path).parts.first? == ".."
    end
  end
end
