require "../spec_helper"
require "file_utils"

# End-to-end `generate` against the built binary in a throwaway fixture repo,
# byte-comparing the emitted wrapper to a golden and asserting the `--check`
# drift gate flips on a hand-edit. Complements the unit specs, which drive the
# same logic through an injected filesystem.
describe "agent-apropos generate (binary)" do
  binary = File.join(Dir.tempdir, "agent-apropos-gen-#{Process.pid}")

  Spec.before_suite do
    status = Process.run(
      "crystal",
      ["build", "src/agent_apropos.cr", "-o", binary],
      output: Process::Redirect::Inherit,
      error: Process::Redirect::Inherit
    )
    raise "failed to build agent-apropos binary for integration specs" unless status.success?
  end

  Spec.after_suite do
    File.delete?(binary)
  end

  it "emits a byte-stable skill wrapper and enforces the --check gate" do
    dir = File.tempname("agent-apropos-gen-repo")
    begin
      Dir.mkdir_p(File.join(dir, "docs/conventions/workflows"))
      File.write(File.join(dir, "docs/conventions/workflows/ship.md"),
        "---\nskill: true\ndescription: \"Use when shipping a feature\"\n---\n\n# Shipping\n\nbody\n")

      # `generate` only writes a skill root whose consumer agent is actually
      # wired (see `Skills.active_roots`) — mark Claude Code and Gemini CLI
      # as such so the roots asserted below get generated.
      Dir.mkdir_p(File.join(dir, ".claude"))
      File.write(File.join(dir, ".claude/settings.json"), "{}")
      Dir.mkdir_p(File.join(dir, ".gemini"))
      File.write(File.join(dir, ".gemini/settings.json"), "{}")

      run = Process.run(binary, ["generate", "--repo-root", dir], output: IO::Memory.new)
      run.exit_code.should eq(0)

      golden = <<-SKILL + "\n"
        ---
        name: ship
        description: Use when shipping a feature
        ---

        <!-- GENERATED by `agent-apropos generate` — do not edit. Edit the source doc instead. -->

        Read `docs/conventions/workflows/ship.md` and follow it.
        SKILL
      File.read(File.join(dir, ".claude/skills/ship/SKILL.md")).should eq(golden)
      File.read(File.join(dir, ".gemini/skills/ship/SKILL.md")).should eq(golden)

      clean = Process.run(binary, ["generate", "--check", "--repo-root", dir], output: IO::Memory.new)
      clean.exit_code.should eq(0)

      File.write(File.join(dir, ".claude/skills/ship/SKILL.md"), "tampered\n")
      dirty = Process.run(binary, ["generate", "--check", "--repo-root", dir], output: IO::Memory.new)
      dirty.exit_code.should eq(1)
    ensure
      FileUtils.rm_rf(dir)
    end
  end

  describe "line endings" do
    doc = "---\nskill: true\ndescription: \"Use when shipping a feature\"\n---\n\n# Shipping\n\nbody\n"
    index = ".cache/agent-apropos/index.json"
    wrapper = ".claude/skills/ship/SKILL.md"

    it "emits a byte-identical index and wrapper from a CRLF checkout as from an LF one" do
      lf_dir = fixture_repo(doc)
      crlf_dir = fixture_repo(doc.gsub("\n", "\r\n"))
      begin
        generate(binary, lf_dir).exit_code.should eq(0)
        generate(binary, crlf_dir).exit_code.should eq(0)

        File.read(File.join(crlf_dir, index)).should eq(File.read(File.join(lf_dir, index)))
        File.read(File.join(crlf_dir, wrapper)).should eq(File.read(File.join(lf_dir, wrapper)))
      ensure
        FileUtils.rm_rf(lf_dir)
        FileUtils.rm_rf(crlf_dir)
      end
    end

    it "reports no drift when the working tree turns CRLF after an LF generate" do
      dir = fixture_repo(doc)
      begin
        generate(binary, dir).exit_code.should eq(0)
        File.write(File.join(dir, "docs/conventions/workflows/ship.md"), doc.gsub("\n", "\r\n"))

        check = Process.run(binary, ["generate", "--check", "--repo-root", dir], output: IO::Memory.new)
        check.exit_code.should eq(0)
      ensure
        FileUtils.rm_rf(dir)
      end
    end
  end
end

private def fixture_repo(doc : String) : String
  dir = File.tempname("agent-apropos-gen-repo")
  Dir.mkdir_p(File.join(dir, "docs/conventions/workflows"))
  File.write(File.join(dir, "docs/conventions/workflows/ship.md"), doc)
  Dir.mkdir_p(File.join(dir, ".claude"))
  File.write(File.join(dir, ".claude/settings.json"), "{}")
  dir
end

private def generate(binary : String, dir : String) : Process::Status
  Process.run(binary, ["generate", "--repo-root", dir], output: IO::Memory.new)
end
