// Generated by `agent-apropos init --tool opencode` — do not edit. Re-run to regenerate.
//
// Bridges agent-apropos's hook system into OpenCode using client.session.prompt
// with noReply:true, which injects convention context into the conversation
// without triggering an AI response.
//
// Scoped rules (path and/or content) inject only when the agent writes:
// tool.execute.before carries the fragment about to be written, and
// tool.execute.after carries it again for edits the before-hook missed.
// A "read" injects nothing — it only tells agent-apropos that a
// convention doc is already in context, so no write re-injects it.
// Both fail open: any error produces no output and never blocks an edit.
// See docs/conventions/README.md for the layer model.

export const AgentAproposPlugin = async ({ worktree, client }) => {
  // Session ID tracked through events; also read from input.sessionID when
  // the plugin event exposes it (undocumented but likely present).
  let sessionID = null

  async function callHook(sub, payload) {
    try {
      const proc = Bun.spawn(["agent-apropos", "hook", sub, "--tool", "opencode"], {
        stdin: new Blob([JSON.stringify(payload)]),
        stdout: "pipe",
        cwd: worktree,
      })
      const text = await new Response(proc.stdout).text()
      const parsed = JSON.parse(text.trim())
      return parsed?.hookSpecificOutput?.additionalContext ?? ""
    } catch {
      return ""
    }
  }

  async function inject(sid, ctx) {
    if (!ctx || !sid) return
    try {
      await client.session.prompt({
        path: { id: sid },
        body: { noReply: true, parts: [{ type: "text", text: ctx }] },
      })
    } catch {
      // Fail open
    }
  }

  function makePayload(input, args, withContent) {
    return {
      session_id: input.sessionID ?? sessionID,
      cwd: worktree,
      tool_name: input.tool,
      tool_input: {
        file_path: args?.filePath,
        ...(withContent ? {
          content:    args?.content,
          new_string: args?.newString,
        } : {}),
      },
    }
  }

  return {
    // Track session ID so inject() can call client.session.prompt.
    event: async ({ event }) => {
      const id = event.properties?.session?.id ?? event.properties?.id
      if (id && (event.type === "session.created" || event.type === "session.updated")) {
        sessionID = id
      }
    },

    // Inject BEFORE the write so the model sees the rule while still in
    // the current tool-processing turn, with the pending content so
    // content regexes match the fragment about to land. Also fires on
    // "read", where agent-apropos emits nothing and only records a
    // convention doc the model has now read for itself. OpenCode
    // delivers the tool arguments in the SECOND callback parameter
    // (output.args) for tool.execute.before; older builds put them on
    // input.args. Read output first, fall back to input.
    "tool.execute.before": async (input, output) => {
      if (!["edit", "write", "apply_patch", "read"].includes(input.tool)) return
      const args = output?.args ?? input.args
      if (!args?.filePath) return
      const ctx = await callHook("pre", makePayload(input, args, true))
      await inject(input.sessionID ?? sessionID, ctx)
    },

    // Inject AFTER the write as well, for rules the before-hook could
    // not resolve (an edit whose newString the before event omits).
    // Here OpenCode carries args on input; the same output-first
    // fallback keeps this robust across versions.
    "tool.execute.after": async (input, output) => {
      if (!["edit", "write", "apply_patch"].includes(input.tool)) return
      const args = output?.args ?? input.args
      if (!args?.filePath) return
      const ctx = await callHook("post", makePayload(input, args, true))
      await inject(input.sessionID ?? sessionID, ctx)
    },
  }
}